version: '3.8'

services:
  server: 
    image: 
      nginx:latest

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
      
    ports:
      - "80:80" 

    container_name: 
      server

    depends_on:
      - app

  app:
    build:
      context: src
      dockerfile: Dockerfile

    container_name:
      myapp

    volumes:
      - ./src:/var/www/laravel

    depends_on:
      - database

  database:
    build: 
      context: mysql
      dockerfile: Dockerfile
    
    container_name: 
      database
    
    # ports:
    #   - 3336:3306

    
